### ISSUE TITLE
SegmentProxy source code

### ISSUE THREAD

**Issue by 89z** [asrashley/dashpiff#2]
I would like to implement a local solution for decrypting PIFF. I checked here:

https://github.com/asrashley/dashpiff/tree/master/SegmentProxy

but I don't see the actual source code that does the decryption. Is that available?

**Comment by 89z** [comment]
Hm, I think this is it:

https://github.com/asrashley/dashpiff/blob/e302edd99d2f1b70f35b249ab3faeb519500f864/SegmentProxy/__init__.py#L40-L43

but maybe what I am wanting is different.

**Comment by asrashley** [comment]
Yes, you need something different. The code in this repository does not decrypt the content, it just patches out some data in the stream. You might want to have a look at https://github.com/asrashley/gst-cencdec for an example of how to decrypt DASH CENC content.
